image: Ubuntu2004  # Используемый образ

branches:
  only:
    - main  # Указываем ветку для сборки

build:
  project: false  # Указываем, что проект Visual Studio не используется

install:
  - chmod +x gradlew  # Добавляем права на выполнение

build_script:
  - echo "Starting build process..."
  - ./gradlew build  # Выполняем сборку проекта

